In [24]:
import pandas as pd
import numpy as np
import boto3
from sklearn.model_selection import train_test_split
import sagemaker
from sagemaker import Session
import io
import sagemaker.amazon.common as smac
import os
from sagemaker.amazon.amazon_estimator import get_image_uri

In [25]:
df = pd.read_csv("loan_dataset.csv")
df.head()

,Gender,Marital_Status,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount_INR,Loan_Term_Years,Credit_History,Existing_Loans,Loan_Status
0,1,1,1,0,60154,57252,2241607,5,1,0,1
1,0,0,0,0,140466,74736,303525,10,1,2,1
2,1,0,0,1,43253,29851,1506744,10,0,0,0
3,1,0,0,1,95940,8159,2435311,30,1,0,1
4,1,0,0,1,185476,57475,920616,10,1,2,1

In [26]:
df.shape

(150000, 11)

In [27]:
X = df.drop(columns=["Loan_Status"])
y = df[["Loan_Status"]]

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
X_train = X_train.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

In [30]:
X_train = X_train.astype("float32")
y_train = y_train.astype("float32")

X_test  = X_test.astype("float32")
y_test  = y_test.astype("float32")

In [31]:
X_train

,Gender,Marital_Status,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount_INR,Loan_Term_Years,Credit_History,Existing_Loans
0,1.0,0.0,1.0,1.0,82484.0,29647.0,910384.0,10.0,1.0,0.0
1,1.0,1.0,0.0,1.0,189045.0,8978.0,943417.0,30.0,1.0,2.0
2,0.0,1.0,0.0,0.0,167888.0,18658.0,1093965.0,25.0,0.0,0.0
3,1.0,1.0,1.0,1.0,64484.0,21575.0,2488758.0,25.0,0.0,2.0
4,0.0,1.0,0.0,0.0,172177.0,37688.0,1066039.0,5.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
119995,0.0,1.0,1.0,1.0,79498.0,54303.0,247094.0,20.0,1.0,2.0
119996,1.0,1.0,1.0,0.0,18884.0,71057.0,915417.0,30.0,1.0,2.0
119997,1.0,0.0,1.0,1.0,49989.0,78812.0,436692.0,25.0,0.0,0.0
119998,0.0,1.0,1.0,0.0,61425.0,29923.0,1787295.0,20.0,1.0,0.0
119999,1.0,0.0,1.0,1.0,138579.0,22761.0,1306165.0,25.0,1.0,0.0

In [32]:
X_test

,Gender,Marital_Status,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount_INR,Loan_Term_Years,Credit_History,Existing_Loans
0,0.0,0.0,0.0,1.0,116855.0,61104.0,1683190.0,15.0,1.0,1.0
1,1.0,0.0,1.0,1.0,100744.0,64858.0,1699382.0,5.0,1.0,2.0
2,0.0,0.0,1.0,0.0,153522.0,62193.0,1193446.0,5.0,1.0,0.0
3,0.0,1.0,1.0,0.0,149489.0,79550.0,970798.0,15.0,1.0,1.0
4,1.0,1.0,0.0,1.0,101723.0,19255.0,2060509.0,10.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
29995,0.0,1.0,1.0,0.0,62390.0,69441.0,2365016.0,5.0,1.0,1.0
29996,0.0,0.0,1.0,1.0,21117.0,55635.0,2134204.0,25.0,1.0,2.0
29997,0.0,1.0,1.0,1.0,44043.0,58323.0,1133394.0,15.0,0.0,2.0
29998,1.0,1.0,1.0,1.0,194825.0,54434.0,771999.0,30.0,1.0,1.0
29999,1.0,0.0,0.0,1.0,180062.0,60556.0,2001085.0,15.0,1.0,0.0

In [33]:
y_train = y_train.iloc[:,0]

In [34]:
y_train

0         1.0
1         1.0
2         1.0
3         0.0
4         1.0
         ...
119995    1.0
119996    1.0
119997    1.0
119998    1.0
119999    1.0
Name: Loan_Status, Length: 120000, dtype: float32

In [35]:
y_test = y_test.iloc[:,0]

In [36]:
sagemaker_session = sagemaker.Session()

bucket_name = "loan-predict"

prefix="linear-predict"

role= sagemaker.get_execution_role()

print(role)

arn:aws:iam::118903272754:role/service-role/AmazonSageMaker-ExecutionRole-20260301T152362

In [37]:
X_train = np.array(X_train)

In [38]:
bucket_name

'loan-predict'

In [39]:
buf = io.BytesIO()

smac.write_numpy_to_dense_tensor(buf, X_train, y_train)
buf.seek(0)

0

In [40]:
key = "loan-data"

boto3.resource("s3").Bucket(bucket_name).Object(os.path.join(prefix, "train", key)).upload_fileobj(buf)

s3_train_data = f"s3://{bucket_name}/{prefix}/train/{key}"

print("Data Uploaded:", s3_train_data)

Data Uploaded: s3://loan-predict/linear-predict/train/loan-data

In [41]:
X_test = np.array(X_test)

buf = io.BytesIO()

smac.write_numpy_to_dense_tensor(buf,X_test,y_test)
buf.seek(0)

key = "loan-date-test"

boto3.resource("s3").Bucket(bucket_name).Object(os.path.join(prefix, "test", key)).upload_fileobj(buf)

s3_train_data = f"s3://{bucket_name}/{prefix}/test/{key}"

print("Data Uploaded:", s3_train_data)

Data Uploaded: s3://loan-predict/linear-predict/test/loan-date-test

In [42]:
output_loaction = f"s3://{bucket_name}/{prefix}/output"
output_loaction

's3://loan-predict/linear-predict/output'

In [43]:
container = sagemaker.image_uris.retrieve("linear-learner",boto3.Session().region_name)

INFO:sagemaker.image_uris:Same images used for training and inference. Defaulting to image scope: inference.
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.

In [44]:
linear = sagemaker.estimator.Estimator(container,role,instance_count=1,instance_type="ml.m5.large",output_path = output_loaction,sagemaker_session=sagemaker_session)

In [45]:
linear.set_hyperparameters(feature_dim=10,predictor_type="regressor",mini_batch_size=4,epochs=6,num_models=32,loss="absolute_loss")

In [46]:
linear.fit({"train":s3_train_data})

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: linear-learner-2026-03-25-02-39-52-376

2026-03-25 02:39:52 Starting - Starting the training job...
2026-03-25 02:40:13 Starting - Preparing the instances for training...
2026-03-25 02:40:35 Downloading - Downloading input data...
2026-03-25 02:41:10 Downloading - Downloading the training image.........
2026-03-25 02:42:41 Training - Training image download completed. Training in progress.Docker entrypoint called with argument(s): train
Running default environment configuration script
[03/25/2026 02:42:43 INFO 139716644329280] Reading default configuration from /opt/amazon/lib/python3.8/site-packages/algorithm/resources/default-input.json: {'mini_batch_size': '1000', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false'}
[03/25/2026 02:42:43 INFO 139716644329280] Merging with provided configuration from /opt/ml/input/config/hyperparameters.json: {'epochs': '6', 'feature_dim': '10', 'loss': 'absolute_loss', 'mini_batch_size': '4', 'num_models': '32', 'predictor_type': 'regressor'}
[03/25/2026 02:42:43 INFO 139716644329280] Final configuration: {'mini_batch_size': '4', 'epochs': '6', 'feature_dim': '10', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': '32', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'absolute_loss', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'regressor'}
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:495: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cons['type'] is 'ineq':
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:743: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.X_min) is not 0:
[03/25/2026 02:42:46 WARNING 139716644329280] Loggers have already been setup.
[03/25/2026 02:42:46 INFO 139716644329280] Final configuration: {'mini_batch_size': '4', 'epochs': '6', 'feature_dim': '10', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': '32', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'absolute_loss', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'regressor'}
[03/25/2026 02:42:46 WARNING 139716644329280] Loggers have already been setup.
Process 7 is a worker.
[03/25/2026 02:42:46 INFO 139716644329280] Using default worker.
[03/25/2026 02:42:46 INFO 139716644329280] Checkpoint loading and saving are disabled.
[2026-03-25 02:42:46.828] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 0, "duration": 12, "num_examples": 1, "num_bytes": 336}
[03/25/2026 02:42:46 INFO 139716644329280] Create Store: local
[2026-03-25 02:42:57.352] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 1, "duration": 10523, "num_examples": 2501, "num_bytes": 840336}
[03/25/2026 02:42:57 INFO 139716644329280] Scaler algorithm parameters
 <algorithm.scaler.ScalerAlgorithmStable object at 0x7f11c99a05b0>
[03/25/2026 02:42:57 INFO 139716644329280] Scaling model computed with parameters:
 {'stdev_label':
[0.37184033]
<NDArray 1 @cpu(0)>, 'stdev_weight':
[4.9997485e-01 4.9998862e-01 4.9994671e-01 4.9998909e-01 5.3823383e+04
 2.3061221e+04 7.1569800e+05 8.5665789e+00 3.9881015e-01 8.1551445e-01]
<NDArray 10 @cpu(0)>, 'mean_label':
[0.8342668]
<NDArray 1 @cpu(0)>, 'mean_weight':
[4.9560142e-01 5.0149864e-01 4.9290273e-01 5.0149924e-01 1.0847784e+05
 4.0029758e+04 1.2744514e+06 1.7581509e+01 8.0158001e-01 1.0128968e+00]
<NDArray 10 @cpu(0)>}
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[03/25/2026 02:42:57 INFO 139716644329280] nvidia-smi: took 0.032 seconds to run.
[03/25/2026 02:42:57 INFO 139716644329280] nvidia-smi identified 0 GPUs.
[03/25/2026 02:42:57 INFO 139716644329280] Number of GPUs being used: 0
#metrics {"StartTime": 1774406577.4487169, "EndTime": 1774406577.44875, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "Meta": "init_train_data_iter"}, "Metrics": {"Total Records Seen": {"sum": 10008.0, "count": 1, "min": 10008, "max": 10008}, "Total Batches Seen": {"sum": 2502.0, "count": 1, "min": 2502, "max": 2502}, "Max Records Seen Between Resets": {"sum": 10004.0, "count": 1, "min": 10004, "max": 10004}, "Max Batches Seen Between Resets": {"sum": 2501.0, "count": 1, "min": 2501, "max": 2501}, "Reset Count": {"sum": 2.0, "count": 1, "min": 2, "max": 2}, "Number of Records Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}, "Number of Batches Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}}}
[2026-03-25 02:44:32.748] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 3, "duration": 95299, "num_examples": 7500, "num_bytes": 2520000}
#metrics {"StartTime": 1774406672.7489634, "EndTime": 1774406672.749244, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 0}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.12758492048084735, "count": 1, "min": 0.12758492048084735, "max": 0.12758492048084735}}}
#metrics {"StartTime": 1774406672.7494485, "EndTime": 1774406672.7494638, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 1}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.1376382813314597, "count": 1, "min": 0.1376382813314597, "max": 0.1376382813314597}}}
#metrics {"StartTime": 1774406672.7495034, "EndTime": 1774406672.7495134, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 2}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.12644375311632952, "count": 1, "min": 0.12644375311632952, "max": 0.12644375311632952}}}
#metrics {"StartTime": 1774406672.749543, "EndTime": 1774406672.749551, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 3}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.1372625852584839, "count": 1, "min": 0.1372625852584839, "max": 0.1372625852584839}}}
#metrics {"StartTime": 1774406672.7495806, "EndTime": 1774406672.7495887, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 4}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.16868700974186263, "count": 1, "min": 0.16868700974186263, "max": 0.16868700974186263}}}
#metrics {"StartTime": 1774406672.749616, "EndTime": 1774406672.7496228, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 5}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.3868385767668486, "count": 1, "min": 0.3868385767668486, "max": 0.3868385767668486}}}
#metrics {"StartTime": 1774406672.7496486, "EndTime": 1774406672.7496557, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 6}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.16384903673529624, "count": 1, "min": 0.16384903673529624, "max": 0.16384903673529624}}}
#metrics {"StartTime": 1774406672.749683, "EndTime": 1774406672.7496912, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 7}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.38789539085924624, "count": 1, "min": 0.38789539085924624, "max": 0.38789539085924624}}}
#metrics {"StartTime": 1774406672.74972, "EndTime": 1774406672.7497277, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 8}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.1283842883527279, "count": 1, "min": 0.1283842883527279, "max": 0.1283842883527279}}}
#metrics {"StartTime": 1774406672.7497551, "EndTime": 1774406672.7497628, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 9}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.13811644289890926, "count": 1, "min": 0.13811644289890926, "max": 0.13811644289890926}}}
#metrics {"StartTime": 1774406672.749792, "EndTime": 1774406672.7498007, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 10}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.12785681123336157, "count": 1, "min": 0.12785681123336157, "max": 0.12785681123336157}}}
#metrics {"StartTime": 1774406672.7498302, "EndTime": 1774406672.7498379, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 11}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.13788887757062912, "count": 1, "min": 0.13788887757062912, "max": 0.13788887757062912}}}
#metrics {"StartTime": 1774406672.7498639, "EndTime": 1774406672.749872, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 12}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.1647002291192611, "count": 1, "min": 0.1647002291192611, "max": 0.1647002291192611}}}
#metrics {"StartTime": 1774406672.7499034, "EndTime": 1774406672.7499113, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 13}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.38988031598478556, "count": 1, "min": 0.38988031598478556, "max": 0.38988031598478556}}}
#metrics {"StartTime": 1774406672.7499392, "EndTime": 1774406672.7499464, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 14}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.16677370072404543, "count": 1, "min": 0.16677370072404543, "max": 0.16677370072404543}}}
#metrics {"StartTime": 1774406672.7499743, "EndTime": 1774406672.7499812, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 15}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.3924434853831927, "count": 1, "min": 0.3924434853831927, "max": 0.3924434853831927}}}
#metrics {"StartTime": 1774406672.750006, "EndTime": 1774406672.750013, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 16}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.35162981685101985, "count": 1, "min": 0.35162981685101985, "max": 0.35162981685101985}}}
#metrics {"StartTime": 1774406672.7500434, "EndTime": 1774406672.7500525, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 17}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.3636476178944111, "count": 1, "min": 0.3636476178944111, "max": 0.3636476178944111}}}
#metrics {"StartTime": 1774406672.7500808, "EndTime": 1774406672.7500885, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 18}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.35203706184724964, "count": 1, "min": 0.35203706184724964, "max": 0.35203706184724964}}}
#metrics {"StartTime": 1774406672.750116, "EndTime": 1774406672.750124, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 19}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.3642072556167841, "count": 1, "min": 0.3642072556167841, "max": 0.3642072556167841}}}
#metrics {"StartTime": 1774406672.7501543, "EndTime": 1774406672.7501621, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 20}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.3900319479942322, "count": 1, "min": 0.3900319479942322, "max": 0.3900319479942322}}}
#metrics {"StartTime": 1774406672.7501926, "EndTime": 1774406672.7502005, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 21}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.5421867314070463, "count": 1, "min": 0.5421867314070463, "max": 0.5421867314070463}}}
#metrics {"StartTime": 1774406672.7502294, "EndTime": 1774406672.7502377, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 22}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.38973750616908076, "count": 1, "min": 0.38973750616908076, "max": 0.38973750616908076}}}
#metrics {"StartTime": 1774406672.7502666, "EndTime": 1774406672.7502747, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 23}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.5458191084777315, "count": 1, "min": 0.5458191084777315, "max": 0.5458191084777315}}}
#metrics {"StartTime": 1774406672.7503057, "EndTime": 1774406672.7503138, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 24}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.44582296683291595, "count": 1, "min": 0.44582296683291595, "max": 0.44582296683291595}}}
#metrics {"StartTime": 1774406672.750341, "EndTime": 1774406672.750349, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 25}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.4509154573529959, "count": 1, "min": 0.4509154573529959, "max": 0.4509154573529959}}}
#metrics {"StartTime": 1774406672.7503786, "EndTime": 1774406672.7503865, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 26}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.4459869563917319, "count": 1, "min": 0.4459869563917319, "max": 0.4459869563917319}}}
#metrics {"StartTime": 1774406672.7504146, "EndTime": 1774406672.750422, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 27}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.45107582104504107, "count": 1, "min": 0.45107582104504107, "max": 0.45107582104504107}}}
#metrics {"StartTime": 1774406672.7504492, "EndTime": 1774406672.7504563, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 28}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.4615448105086883, "count": 1, "min": 0.4615448105086883, "max": 0.4615448105086883}}}
#metrics {"StartTime": 1774406672.7504833, "EndTime": 1774406672.7504914, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 29}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.518536595493555, "count": 1, "min": 0.518536595493555, "max": 0.518536595493555}}}
#metrics {"StartTime": 1774406672.7505205, "EndTime": 1774406672.7505286, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 30}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.4605398672272762, "count": 1, "min": 0.4605398672272762, "max": 0.4605398672272762}}}
#metrics {"StartTime": 1774406672.750556, "EndTime": 1774406672.750564, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 31}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.5217884987006585, "count": 1, "min": 0.5217884987006585, "max": 0.5217884987006585}}}
[03/25/2026 02:44:32 INFO 139716644329280] #quality_metric: host=algo-1, epoch=0, train absolute_loss_objective <loss>=0.12758492048084735
[03/25/2026 02:44:32 INFO 139716644329280] #early_stopping_criteria_metric: host=algo-1, epoch=0, criteria=absolute_loss_objective, value=0.12644375311632952
[03/25/2026 02:44:32 INFO 139716644329280] Epoch 0: Loss improved. Updating best model
[03/25/2026 02:44:32 INFO 139716644329280] Saving model for epoch: 0
[03/25/2026 02:44:32 INFO 139716644329280] Saved checkpoint to "/tmp/tmpng7q8jog/mx-mod-0000.params"
[03/25/2026 02:44:32 INFO 139716644329280] #progress_metric: host=algo-1, completed 16.666666666666668 % of epochs

In [47]:
linear_regresor = linear.deploy(initial_instance_count=1,instance_type="ml.m5.large")

INFO:sagemaker:Creating model with name: linear-learner-2026-03-25-02-53-26-050
INFO:sagemaker:Creating endpoint-config with name linear-learner-2026-03-25-02-53-26-050
INFO:sagemaker:Creating endpoint with name linear-learner-2026-03-25-02-53-26-050

-------!

In [48]:
linear_regresor.serializer = sagemaker.serializers.CSVSerializer()
linear_regresor.deserializer = sagemaker.deserializers.JSONDeserializer()

In [49]:
result = linear_regresor.predict(X_test)

In [50]:
result

{'predictions': [{'score': 1.000004529953003},
  {'score': 0.9999977946281433},
  {'score': 0.9999905228614807},
  {'score': 0.9999881982803345},
  {'score': -2.4237935576820746e-05},
  {'score': -2.034776844084263e-05},
  {'score': 0.9999919533729553},
  {'score': 0.9999794960021973},
  {'score': 0.9999815225601196},
  {'score': 0.9999939799308777},
  {'score': 0.9999855160713196},
  {'score': 0.9999948143959045},
  {'score': 0.9999849200248718},
  {'score': 0.9999756217002869},
  {'score': 0.9999884366989136},
  {'score': 0.9999917149543762},
  {'score': 0.9999935030937195},
  {'score': 0.9999693632125854},
  {'score': 0.9999883770942688},
  {'score': 0.9999827146530151},
  {'score': 0.9999880194664001},
  {'score': -1.2662278095376678e-05},
  {'score': 0.9999834299087524},
  {'score': 0.9999733567237854},
  {'score': 0.9999752640724182},
  {'score': -2.5526705940137617e-05},
  {'score': -1.5947418432915583e-05},
  {'score': -1.087788950826507e-05},
  {'score': -2.5192452085320838e-05},
  {'score': 1.0000042915344238},
  {'score': 0.9999822378158569},
  {'score': 0.9999961256980896},
  {'score': 0.9999854564666748},
  {'score': 0.999961793422699},
  {'score': 0.9999901652336121},
  {'score': 0.9999735951423645},
  {'score': 1.0000030994415283},
  {'score': 0.9999638199806213},
  {'score': 0.999998152256012},
  {'score': 0.9999983906745911},
  {'score': 0.9999849200248718},
  {'score': 0.9999925494194031},
  {'score': 0.9999955296516418},
  {'score': 0.9999890923500061},
  {'score': 0.9999950528144836},
  {'score': 0.9999987483024597},
  {'score': 0.9999918341636658},
  {'score': 0.9999807476997375},
  {'score': -1.2873626474174671e-05},
  {'score': 0.99998539686203},
  {'score': -1.3940215467300732e-05},
  {'score': -3.11819530907087e-05},
  {'score': 0.9999883770942688},
  {'score': 0.9999907612800598},
  {'score': 0.9999896883964539},
  {'score': 0.9999938607215881},
  {'score': 0.9999856352806091},
  {'score': 1.000004768371582},
  {'score': 0.9999804496765137},
  {'score': 0.9999911189079285},
  {'score': 0.9999918341636658},
  {'score': 0.9999924302101135},
  {'score': 0.9999924302101135},
  {'score': 0.9999929070472717},
  {'score': -2.7726648113457486e-05},
  {'score': 0.9999828338623047},
  {'score': 0.9999861121177673},
  {'score': 0.9999906420707703},
  {'score': -2.9957713195472024e-05},
  {'score': 0.999988317489624},
  {'score': 1.0000042915344238},
  {'score': -4.367328074295074e-06},
  {'score': 1.0000066757202148},
  {'score': 1.0000088214874268},
  {'score': 0.9999948143959045},
  {'score': -1.6752814190112986e-05},
  {'score': -2.8947697501280345e-05},
  {'score': -2.773975757008884e-05},
  {'score': 0.9999938607215881},
  {'score': 0.9999930262565613},
  {'score': -3.141252454952337e-05},
  {'score': 0.9999727010726929},
  {'score': 1.0000050067901611},
  {'score': 0.9999868273735046},
  {'score': -1.5892042938503437e-05},
  {'score': 0.9999940991401672},
  {'score': 0.9999698996543884},
  {'score': 0.9999837279319763},
  {'score': 0.9999902844429016},
  {'score': -2.552912883402314e-05},
  {'score': 0.9999868869781494},
  {'score': 0.9999933838844299},
  {'score': 0.9999781250953674},
  {'score': -1.7396067050867714e-05},
  {'score': -1.3966631740913726e-05},
  {'score': 0.9999915957450867},
  {'score': 0.9999808669090271},
  {'score': -1.1523110515554436e-05},
  {'score': 0.9999809265136719},
  {'score': 0.9999942183494568},
  {'score': 0.9999843835830688},
  {'score': 0.9999813437461853},
  {'score': 0.999983012676239},
  {'score': -9.620458513381891e-06},
  {'score': 0.9999836087226868},
  {'score': -3.266496059950441e-05},
  {'score': 0.9999904036521912},
  {'score': 0.9999919533729553},
  {'score': 0.99998539686203},
  {'score': -3.716944775078446e-05},
  {'score': -1.1548027032404207e-05},
  {'score': 0.999978244304657},
  {'score': 0.9999863505363464},
  {'score': 0.9999843239784241},
  {'score': -1.849311047408264e-05},
  {'score': -2.294718797202222e-06},
  {'score': 1.0000076293945312},
  {'score': 0.9999755620956421},
  {'score': 0.9999986290931702},
  {'score': -1.860904012573883e-05},
  {'score': 0.999976396560669},
  {'score': -2.5431771064177155e-05},
  {'score': -3.557230593287386e-05},
  {'score': 1.0000004768371582},
  {'score': 0.9999839067459106},
  {'score': 0.9999847412109375},
  {'score': 0.9999808669090271},
  {'score': 0.9999865293502808},
  {'score': 0.999968409538269},
  {'score': 1.000002384185791},
  {'score': 0.9999828338623047},
  {'score': -1.3157774446881376e-05},
  {'score': 0.9999935030937195},
  {'score': 0.9999799132347107},
  {'score': 0.9999809265136719},
  {'score': -1.076038370229071e-05},
  {'score': 0.9999839663505554},
  {'score': 0.9999706149101257},
  {'score': -3.296877184766345e-05},
  {'score': 0.9999880790710449},
  {'score': 1.0000004768371582},
  {'score': 0.9999879002571106},
  {'score': 1.0000038146972656},
  {'score': -2.1668196495738812e-05},
  {'score': 0.9999886751174927},
  {'score': 0.999993622303009},
  {'score': 0.9999980330467224},
  {'score': 0.9999755620956421},
  {'score': 0.9999867081642151},
  {'score': 0.9999775886535645},
  {'score': -1.5907025954220444e-05},
  {'score': 0.9999791383743286},
  {'score': 1.0000085830688477},
  {'score': 0.9999756813049316},
  {'score': -3.954457497457042e-05},
  {'score': -5.988075827190187e-06},
  {'score': 1.0000009536743164},
  {'score': 0.9999873638153076},
  {'score': -4.1380306356586516e-05},
  {'score': 0.9999958872795105},
  {'score': 0.9999870657920837},
  {'score': 0.9999943375587463},
  {'score': 0.9999915957450867},
  {'score': 0.9999744296073914},
  {'score': 0.9999950528144836},
  {'score': 0.9999744892120361},
  {'score': 0.9999752640724182},
  {'score': 0.99998539686203},
  {'score': 0.9999988675117493},
  {'score': 0.9999879002571106},
  {'score': 0.9999915957450867},
  {'score': 1.0000066757202148},
  {'score': 0.9999985098838806},
  {'score': 0.9999881982803345},
  {'score': 0.9999786019325256},
  {'score': 1.0000040531158447},
  {'score': 0.9999861121177673},
  {'score': 0.9999794960021973},
  {'score': 0.999994695186615},
  {'score': 0.9999873042106628},
  {'score': 0.9999919533729553},
  {'score': 1.0000019073486328},
  {'score': 0.9999861121177673},
  {'score': 0.9999771118164062},
  {'score': -1.7040361854014918e-05},
  {'score': -2.249984027002938e-05},
  {'score': 1.0000028610229492},
  {'score': 1.000009536743164},
  {'score': 0.999972403049469},
  {'score': 0.9999824166297913},
  {'score': 0.9999802112579346},
  {'score': 0.9999983906745911},
  {'score': 0.9999968409538269},
  {'score': 0.9999992251396179},
  {'score': -6.969753940211376e-06},
  {'score': 0.9999836683273315},
  {'score': 0.9999971985816956},
  {'score': 0.9999803900718689},
  {'score': -1.371791586279869e-05},
  {'score': 0.9999751448631287},
  {'score': -1.846880513767246e-05},
  {'score': -2.0737741579068825e-05},
  {'score': 0.9999881982803345},
  {'score': 5.491807314683683e-06},
  {'score': 0.9999781250953674},
  {'score': 0.999993622303009},
  {'score': 0.9999762177467346},
  {'score': 0.9999852180480957},
  {'score': 0.9999744296073914},
  {'score': 0.9999746680259705},
  {'score': 0.9999851584434509},
  {'score': 0.9999799728393555},
  {'score': 0.9999851584434509},
  {'score': 0.999985933303833},
  {'score': -3.049810038646683e-05},
  {'score': 0.9999816417694092},
  {'score': 0.9999931454658508},
  {'score': 0.9999967217445374},
  {'score': 0.9999861121177673},
  {'score': 0.9999927878379822},
  {'score': 0.9999976754188538},
  {'score': 0.9999822378158569},
  {'score': 0.9999964833259583},
  {'score': 0.9999962449073792},
  {'score': -1.891969623102341e-05},
  {'score': 1.0000050067901611},
  {'score': 0.9999933838844299},
  {'score': 0.9999754428863525},
  {'score': -1.1068361345678568e-05},
  {'score': 0.9999889731407166},
  {'score': -1.2997090379940346e-05},
  {'score': 0.9999865293502808},
  {'score': 0.9999905228614807},
  {'score': 0.9999722838401794},
  {'score': -1.5334913769038394e-05},
  {'score': 0.9999768137931824},
  {'score': 0.9999870657920837},
  {'score': 0.9999767541885376},
  {'score': 0.9999937415122986},
  {'score': 0.9999794960021973},
  {'score': 0.999997079372406},
  {'score': 0.9999797940254211},
  {'score': 0.9999866485595703},
  {'score': 0.9999962449073792},
  {'score': 1.0000016689300537},
  {'score': 0.9999909996986389},
  {'score': 0.9999964833259583},
  {'score': 0.9999909996986389},
  {'score': 0.9999952912330627},
  {'score': 0.9999837875366211},
  {'score': 0.9999848008155823},
  {'score': 1.0000011920928955},
  {'score': 0.9999882578849792},
  {'score': 1.000002145767212},
  {'score': 0.9999931454658508},
  {'score': 0.9999831914901733},
  {'score': 0.9999855160713196},
  {'score': 1.0000033378601074},
  {'score': -9.754747225088067e-06},
  {'score': 0.9999806880950928},
  {'score': 0.9999808073043823},
  {'score': 0.999983012676239},
  {'score': 0.9999711513519287},
  {'score': 0.9999780058860779},
  {'score': 0.9999752044677734},
  {'score': 0.999997079372406},
  {'score': 0.9999913573265076},
  {'score': 0.9999943375587463},
  {'score': 0.999985933303833},
  {'score': 0.9999882578849792},
  {'score': -3.0150895327096805e-05},
  {'score': 0.99998539686203},
  {'score': -2.4250841306638904e-05},
  {'score': 0.9999999403953552},
  {'score': 0.9999913573265076},
  {'score': -1.0156156349694356e-05},
  {'score': 0.999992311000824},
  {'score': 0.9999827146530151},
  {'score': 0.9999764561653137},
  {'score': 0.9999925494194031},
  {'score': 0.9999942183494568},
  {'score': 1.0000011920928955},
  {'score': 0.9999875426292419},
  {'score': 0.9999839067459106},
  {'score': -1.1000383892678656e-05},
  {'score': 0.9999878406524658},
  {'score': 1.0000014305114746},
  {'score': 0.9999914765357971},
  {'score': 0.9999956488609314},
  {'score': 0.9999812245368958},
  {'score': 0.9999797344207764},
  {'score': 0.9999878406524658},
  {'score': -2.7872623832081445e-05},
  {'score': 0.9999834299087524},
  {'score': 0.9999738931655884},
  {'score': 0.9999815225601196},
  {'score': 0.9999774098396301},
  {'score': 0.9999973177909851},
  {'score': 0.9999955296516418},
  {'score': -1.9936547687393613e-05},
  {'score': 0.9999752640724182},
  {'score': 0.9999943375587463},
  {'score': 0.9999874234199524},
  {'score': 0.9999877214431763},
  {'score': 0.9999976754188538},
  {'score': 0.9999976754188538},
  {'score': 0.9999882578849792},
  {'score': -2.5340908905491233e-05},
  {'score': 0.9999993443489075},
  {'score': -8.442737453151494e-06},
  {'score': -2.014308665820863e-05},
  {'score': 1.000004529953003},
  {'score': 0.9999755620956421},
  {'score': 0.9999900460243225},
  {'score': 0.999981164932251},
  {'score': -8.646072274132166e-06},
  {'score': -1.8312797692487948e-05},
  {'score': -2.4485148969688453e-05},
  {'score': 0.9999938607215881},
  {'score': 0.9999933838844299},
  {'score': 0.999983549118042},
  {'score': 0.9999961256980896},
  {'score': 0.9999797940254211},
  {'score': 0.9999839663505554},
  {'score': 0.9999815821647644},
  {'score': 0.9999854564666748},
  {'score': 0.999986469745636},
  {'score': 0.9999919533729553},
  {'score': -3.363978612469509e-05},
  {'score': 0.9999886155128479},
  {'score': 0.9999918341636658},
  {'score': 1.0000085830688477},
  {'score': 0.999983012676239},
  {'score': 0.9999845623970032},
  {'score': 0.9999746084213257},
  {'score': 1.0000066757202148},
  {'score': 0.999993622303009},
  {'score': 0.9999811053276062},
  {'score': 0.9999890923500061},
  {'score': -8.48063973535318e-06},
  {'score': 0.9999783635139465},
  {'score': 0.9999837875366211},
  {'score': 0.9999838471412659},
  {'score': 0.9999793767929077},
  {'score': 0.9999871850013733},
  {'score': -2.204222619184293e-05},
  {'score': -2.7419684556662105e-05},
  {'score': 0.9999842047691345},
  {'score': 0.9999896883964539},
  {'score': 0.9999954104423523},
  {'score': 0.9999870657920837},
  {'score': 0.999993622303009},
  {'score': 0.9999677538871765},
  {'score': -3.801702041528188e-05},
  {'score': 0.9999820590019226},
  {'score': -2.5439292585360818e-05},
  {'score': 0.9999841451644897},
  {'score': 0.9999747276306152},
  {'score': 0.9999867677688599},
  {'score': 0.9999841451644897},
  {'score': 0.9999963641166687},
  {'score': 0.9999813437461853},
  {'score': 0.9999833703041077},
  {'score': 0.9999788403511047},
  {'score': 0.9999976754188538},
  {'score': 0.9999796152114868},
  {'score': 0.9999951720237732},
  {'score': 0.9999871850013733},
  {'score': 1.0000009536743164},
  {'score': 0.9999913573265076},
  {'score': -1.2287895515328273e-05},
  {'score': 0.9999870657920837},
  {'score': 0.9999790787696838},
  {'score': 0.9999954104423523},
  {'score': 0.9999794960021973},
  {'score': 0.9999966025352478},
  {'score': 0.9999839663505554},
  {'score': 0.9999754428863525},
  {'score': 0.9999706745147705},
  {'score': -2.3660391889279708e-05},
  {'score': 0.9999895691871643},
  {'score': 0.9999759197235107},
  {'score': 0.999989926815033},
  {'score': 0.9999876022338867},
  {'score': 0.9999774694442749},
  {'score': 1.0000040531158447},
  {'score': 0.9999777674674988},
  {'score': -9.922254321281798e-06},
  {'score': 0.9999913573265076},
  {'score': 0.9999712705612183},
  {'score': 0.9999940991401672},
  {'score': -2.446170401526615e-05},
  {'score': 0.9999716281890869},
  {'score': 0.9999772310256958},
  {'score': 0.9999886751174927},
  {'score': -3.4795277315424755e-05},
  {'score': 0.9999815225601196},
  {'score': 0.9999852180480957},
  {'score': 0.9999931454658508},
  {'score': 0.9999752640724182},
  {'score': 0.9999741315841675},
  {'score': -2.1027997718192637e-05},
  {'score': 1.0000061988830566},
  {'score': 0.9999938607215881},
  {'score': -1.5116825125005562e-05},
  {'score': 0.9999796748161316},
  {'score': 0.9999869465827942},
  {'score': 0.9999844431877136},
  {'score': 0.9999778866767883},
  {'score': 0.9999917149543762},
  {'score': 0.9999827146530151},
  {'score': 0.9999940991401672},
  {'score': 1.0000026226043701},
  {'score': 0.999973475933075},
  {'score': 1.0000019073486328},
  {'score': 0.9999902844429016},
  {'score': 0.9999669790267944},
  {'score': 0.9999638795852661},
  {'score': 0.9999798536300659},
  {'score': 0.9999960064888},
  {'score': 0.9999739527702332},
  {'score': 0.999992311000824},
  {'score': -1.991201497730799e-05},
  {'score': 1.0000009536743164},
  {'score': 0.9999806880950928},
  {'score': 0.9999858736991882},
  {'score': 0.9999886155128479},
  {'score': 0.99998539686203},
  {'score': 0.999981164932251},
  {'score': 0.9999686479568481},
  {'score': -8.399311809625942e-06},
  {'score': 1.0000035762786865},
  {'score': 0.9999913573265076},
  {'score': 0.9999843835830688},
  {'score': 0.9999834299087524},
  {'score': -1.3799713997286744e-05},
  {'score': 0.9999812245368958},
  {'score': 0.9999918341636658},
  {'score': 0.9999995827674866},
  {'score': 0.9999932646751404},
  {'score': 0.9999861717224121},
  {'score': -1.1349933629389852e-05},
  {'score': 0.9999979138374329},
  {'score': 0.9999937415122986},
  {'score': 2.0951556507498026e-06},
  {'score': -2.9554168577305973e-05},
  {'score': 1.0000016689300537},
  {'score': 0.9999843835830688},
  {'score': 0.9999949336051941},
  {'score': 1.0000028610229492},
  {'score': 0.9999846816062927},
  {'score': 0.9999930262565613},
  {'score': 0.9999856352806091},
  {'score': -2.6347959646955132e-05},
  {'score': -1.776489443727769e-05},
  {'score': 1.000009536743164},
  {'score': 0.9999877214431763},
  {'score': 0.9999874234199524},
  {'score': 0.9999814033508301},
  {'score': -2.4839766410877928e-05},
  {'score': 0.9999825954437256},
  {'score': 0.9999822974205017},
  {'score': -1.6073408914962783e-06},
  {'score': 0.9999868869781494},
  {'score': 0.9999825358390808},
  {'score': 0.9999724626541138},
  {'score': 0.999987006187439},
  {'score': 0.9999901652336121},
  {'score': 0.99998539686203},
  {'score': 0.9999819397926331},
  {'score': 0.999975860118866},
  {'score': -2.171042433474213e-05},
  {'score': 0.9999773502349854},
  {'score': 0.9999911189079285},
  {'score': 1.0000035762786865},
  {'score': 0.9999938607215881},
  {'score': 0.9999991059303284},
  {'score': 1.0000026226043701},
  {'score': -3.5224926250521094e-05},
  {'score': 0.9999843835830688},
  {'score': -1.5275472833309323e-05},
  {'score': 0.9999881982803345},
  {'score': 0.9999887347221375},
  {'score': 0.9999828934669495},
  {'score': 1.0000019073486328},
  {'score': 1.000009536743164},
  {'score': 0.9999963641166687},
  {'score': 1.0000028610229492},
  {'score': 0.9999775290489197},
  {'score': 0.9999676942825317},
  {'score': -1.9907969544874504e-05},
  {'score': 0.9999921917915344},
  {'score': -9.158928151009604e-06},
  {'score': 0.9999915957450867},
  {'score': 0.9999772906303406},
  {'score': 0.9999875426292419},
  {'score': 0.9999883770942688},
  {'score': 0.9999772310256958},
  {'score': 0.9999929070472717},
  {'score': 1.0000011920928955},
  {'score': 0.9999900460243225},
  {'score': 0.9999783039093018},
  {'score': -1.4637726053479128e-06},
  {'score': 1.000011920928955},
  {'score': 0.9999943375587463},
  {'score': -2.779312853817828e-05},
  {'score': 0.9999843835830688},
  {'score': 0.9999906420707703},
  {'score': -7.974576874403283e-07},
  {'score': 0.9999771118164062},
  {'score': 1.0000038146972656},
  {'score': 0.9999837279319763},
  {'score': 0.9999768137931824},
  {'score': -1.871193671831861e-05},
  {'score': 0.9999850988388062},
  {'score': 0.9999862313270569},
  {'score': -2.3007287381915376e-05},
  {'score': 0.9999898076057434},
  {'score': 0.9999856352806091},
  {'score': 0.9999813437461853},
  {'score': 0.9999854564666748},
  {'score': 0.9999939799308777},
  {'score': -2.862164910766296e-05},
  {'score': 0.9999779462814331},
  {'score': 0.999989926815033},
  {'score': 0.9999886751174927},
  {'score': -2.898911407100968e-05},
  {'score': 0.9999938607215881},
  {'score': 0.9999629855155945},
  {'score': 0.9999850988388062},
  {'score': 0.9999850988388062},
  {'score': 1.0000059604644775},
  {'score': 0.9999663233757019},
  {'score': 0.9999940991401672},
  {'score': 0.9999840259552002},
  {'score': -3.059593291254714e-05},
  {'score': 0.9999836087226868},
  {'score': 0.9999691247940063},
  {'score': 0.9999962449073792},
  {'score': -1.1291531336610205e-05},
  {'score': 0.9999730587005615},
  {'score': 0.9999895691871643},
  {'score': -7.370802450168412e-06},
  {'score': 0.9999976754188538},
  {'score': 0.9999771118164062},
  {'score': 0.9999743103981018},
  {'score': 0.999977171421051},
  {'score': -2.6814996090251952e-05},
  {'score': 0.9999845027923584},
  {'score': 0.9999806880950928},
  {'score': 1.000000238418579},
  {'score': 0.9999945759773254},
  {'score': -4.9397633119951934e-05},
  {'score': 0.9999865293502808},
  {'score': 0.9999890327453613},
  {'score': 0.9999927878379822},
  {'score': 0.9999831914901733},
  {'score': 0.9999904036521912},
  {'score': 0.9999833703041077},
  {'score': 0.9999878406524658},
  {'score': 0.9999989867210388},
  {'score': 0.9999815225601196},
  {'score': -1.8882810763898306e-05},
  {'score': 0.9999955296516418},
  {'score': 0.9999955296516418},
  {'score': 0.9999987483024597},
  {'score': 0.9999929070472717},
  {'score': 0.9999919533729553},
  {'score': -3.059289883822203e-05},
  {'score': 0.9999895691871643},
  {'score': 0.9999838471412659},
  {'score': -1.2892066479253117e-05},
  {'score': 0.9999926686286926},
  {'score': 0.9999752044677734},
  {'score': 0.9999974370002747},
  {'score': 0.9999943375587463},
  {'score': -2.0620380382752046e-05},
  {'score': 0.9999935030937195},
  {'score': 0.999983549118042},
  {'score': 0.9999850392341614},
  {'score': 0.999993622303009},
  {'score': 1.0000061988830566},
  {'score': 1.0000007152557373},
  {'score': 0.9999862909317017},
  {'score': -1.2347412848612294e-05},
  {'score': 0.9999951720237732},
  {'score': 0.999994695186615},
  {'score': 1.000007152557373},
  {'score': -4.5151122321840376e-05},
  {'score': 0.9999691843986511},
  {'score': -2.1133600967004895e-05},
  {'score': 0.9999798536300659},